import { PartialTheme } from "@fluentui/theme";

export const lightTheme : PartialTheme = {
        palette: {
          // themePrimary: '#fe7c16',
          // themeLighterAlt: '#fffaf6',
          // themeLighter: '#ffeada',
          // themeLight: '#ffd8b9',
          // themeTertiary: '#ffb074',
          // themeSecondary: '#ff8b33',
          // themeDarkAlt: '#e66f15',
          // themeDark: '#c25e11',
          // themeDarker: '#8f450d',
          // neutralLighterAlt: '#faf9f8',
          // neutralLighter: '#f3f2f1',
          // neutralLight: '#edebe9',
          // neutralQuaternaryAlt: '#e1dfdd',
          // neutralQuaternary: '#d0d0d0',
          // neutralTertiaryAlt: '#c8c6c4',
          // neutralTertiary: '#a19f9d',
          // neutralSecondary: '#605e5c',
          // neutralPrimaryAlt: '#3b3a39',
          // neutralPrimary: '#323130',
          // neutralDark: '#201f1e',
          // black: '#000000',
          // white: '#ffffff',
            themePrimary: '#67b346',
            themeLighterAlt: '#f8fcf6',
            themeLighter: '#e2f3db',
            themeLight: '#cae8be',
            themeTertiary: '#9cd185',
            themeSecondary: '#75bc57',
            themeDarkAlt: '#5ca13f',
            themeDark: '#4e8835',
            themeDarker: '#396427',
            neutralLighterAlt: '#faf9f8',
            neutralLighter: '#f3f2f1',
            neutralLight: '#edebe9',
            neutralQuaternaryAlt: '#e1dfdd',
            neutralQuaternary: '#d0d0d0',
            neutralTertiaryAlt: '#c8c6c4',
            neutralTertiary: '#a19f9d',
            neutralSecondary: '#605e5c',
            neutralPrimaryAlt: '#3b3a39',
            neutralPrimary: '#323130',
            neutralDark: '#201f1e',
            black: '#000000',
            white: '#ffffff',
        },
        components: { Modal: { styles: { root:{header: { borderTop: `4px solid red` }} } } },
};
export const darkTheme : PartialTheme = {
    palette: {
        // themePrimary: '#fe7c16',
        // themeLighterAlt: '#fffaf6',
        // themeLighter: '#ffeada',
        // themeLight: '#ffd8b9',
        // themeTertiary: '#ffb074',
        // themeSecondary: '#ff8b33',
        // themeDarkAlt: '#e66f15',
        // themeDark: '#c25e11',
        // themeDarker: '#8f450d',
        // neutralLighterAlt: '#323232',
        // neutralLighter: '#313131',
        // neutralLight: '#2f2f2f',
        // neutralQuaternaryAlt: '#2c2c2c',
        // neutralQuaternary: '#2a2a2a',
        // neutralTertiaryAlt: '#282828',
        // neutralTertiary: '#c8c8c8',
        // neutralSecondary: '#d0d0d0',
        // neutralPrimaryAlt: '#dadada',
        // neutralPrimary: '#ffffff',
        // neutralDark: '#f4f4f4',
        // black: '#f8f8f8',
        // white: '#333333',
        themePrimary: '#67b346',
        themeLighterAlt: '#040703',
        themeLighter: '#101d0b',
        themeLight: '#1f3615',
        themeTertiary: '#3d6b2a',
        themeSecondary: '#5a9d3d',
        themeDarkAlt: '#73ba54',
        themeDark: '#85c56a',
        themeDarker: '#a1d48c',
        neutralLighterAlt: '#323232',
        neutralLighter: '#313131',
        neutralLight: '#2f2f2f',
        neutralQuaternaryAlt: '#2c2c2c',
        neutralQuaternary: '#2a2a2a',
        neutralTertiaryAlt: '#282828',
        neutralTertiary: '#c8c8c8',
        neutralSecondary: '#d0d0d0',
        neutralPrimaryAlt: '#dadada',
        neutralPrimary: '#ffffff',
        neutralDark: '#f4f4f4',
        black: '#f8f8f8',
        white: '#333333',
    }
};